---
title: "hw8"
author: "Colin Yao"
date: "11/28/2020"
output: html_document
---

```{r}
library(readr)
library(randomForest)
library(reshape2)
setwd("~/Desktop/ECON 487/hw2")
oj <- read_csv("oj.csv")
df1 <-oj
df1$week<-df1$week+1
myvars <- c("price", "week", "brand","store")
df1 <- df1[myvars]
lagged <- merge(oj, df1, by=c("brand","store","week"))
lagged=lagged[order(lagged$week,lagged$store),]
lagged=lagged[order(lagged$store,lagged$week),]
colnames(lagged)[18] <- "lagged_price"
colnames(lagged)[6] <- "price"
oj_prices <-lagged[,1:6]
oj_wide <- dcast(oj_prices, store + week ~ brand)
colnames(oj_wide)[3] <- "P_Dom"
colnames(oj_wide)[4] <- "P_MM"
colnames(oj_wide)[5] <- "P_Trop"
oj_cross <- merge(lagged, oj_wide, by=c("week","store"))
oj_cross$brand = factor(oj_cross$brand)
oj_cross$price <- log(oj_cross$price)
```

```{r echo=TRUE}
#) tropicana
trop_cross <- subset(oj_cross, brand=="tropicana")
Q_X <- trop_cross[,-c(6)]
Q.rf <- randomForest(logmove ~., data=Q_X, ntree=5, keep.forest=TRUE)
Q_res_trop <- Q_X$logmove - predict(Q.rf, Q_X)
P_X <- trop_cross[,-c(4)]
P.rf <- randomForest(price ~., data=P_X, ntree=5, keep.forest=TRUE)
P_res_trop <- P_X$price - predict(P.rf, P_X)
fit_trop <- lm(Q_res_trop ~ P_res_trop)
summary(fit_trop)
```

```{r echo=TRUE}
#) minute.maid
MM_cross <- subset(oj_cross, brand=="minute.maid")
Q_X <- MM_cross[,-c(6)]
Q.rf <- randomForest(logmove ~., data=Q_X, ntree=5, keep.forest=TRUE)
Q_res_MM <- Q_X$logmove - predict(Q.rf, Q_X)
P_X <- MM_cross[,-c(4)]
P.rf <- randomForest(price ~., data=P_X, ntree=5, keep.forest=TRUE)
P_res_MM <- P_X$price - predict(P.rf, P_X)
fit_MM <- lm(Q_res_MM ~ P_res_MM)
summary(fit_MM)
```

```{r echo=TRUE}
#) dominicks
dom_cross <- subset(oj_cross, brand=="dominicks")
Q_X <- dom_cross[,-c(6)]
Q.rf <- randomForest(logmove ~., data=Q_X, ntree=5, keep.forest=TRUE)
Q_res_dom <- Q_X$logmove - predict(Q.rf, Q_X)
P_X <- dom_cross[,-c(4)]
P.rf <- randomForest(price ~., data=P_X, ntree=5, keep.forest=TRUE)
P_res_dom <- P_X$price - predict(P.rf, P_X)
fit_dom <- lm(Q_res_dom ~ P_res_dom)
summary(fit_dom)
```

```{r echo=TRUE}
rownames = c("Q Trop", "Q MM", "Q Dom")
colnames = c("P Trop", "P MM", "P Dom")
Elast_matrix <- matrix(,3,3, dimnames = list(rownames, colnames))
regcrosst = glm(Q_res_trop ~ P_res_trop + P_res_MM + P_res_dom)
regcrossm = glm(Q_res_MM ~ P_res_trop + P_res_MM + P_res_dom)
regcrossd = glm(Q_res_dom ~ P_res_trop + P_res_MM + P_res_dom)
Elast_matrix[1,1] <- coef(regcrosst)["P_res_trop"] 
Elast_matrix[1,2] <- coef(regcrosst)["P_res_MM"] 
Elast_matrix[1,3] <- coef(regcrosst)["P_res_dom"] 
Elast_matrix[2,1] <- coef(regcrossm)["P_res_trop"] 
Elast_matrix[2,2] <- coef(regcrossm)["P_res_MM"] 
Elast_matrix[2,3] <- coef(regcrossm)["P_res_dom"] 
Elast_matrix[3,1] <- coef(regcrossd)["P_res_trop"] 
Elast_matrix[3,2] <- coef(regcrossd)["P_res_MM"] 
Elast_matrix[3,3] <- coef(regcrossd)["P_res_dom"] 
Elast_matrix
```






