---
title: "hw9"
author: "Colin Yao"
date: "12/8/2020"
output: html_document
---

```{r echo=TRUE, message=FALSE}
#load data
library(readr)
library(randomForest)
library(reshape2)
library(rpart)
setwd("~/Desktop/ECON 487/hw2")
mydata <- read_csv("oj.csv")
oj <- mydata
colnames(mydata)[1-17]
#reduce decimal places
is.num=sapply(mydata, is.numeric)
mydata[is.num] = lapply(mydata[is.num], round, 4)
```

```{r echo=TRUE, message=FALSE}
#CREATE LAGGED DATA with recycled code
df1 <-oj
df1$week<-df1$week+1  
df2 <-oj
df2$week<-df1$week+2  

myvars <- c("price", "logmove","week", "brand","store", "feat")
df1 <- df1[myvars]
names(df1)[names(df1)=="price"] = "price_t1"
names(df1)[names(df1)=="feat"] = "feat_t1"
names(df1)[names(df1)=="logmove"] = "logmove_t1"
lagged <- merge(oj, df1, by=c("brand","store","week"))
lagged=lagged[order(lagged$week,lagged$store),]
lagged=lagged[order(lagged$store,lagged$week),]
#Now do the same this with two weeks of lagged data.

df2 <- df2[myvars]
names(df2)[names(df2)=="price"] = "price_t2"
names(df2)[names(df2)=="feat"] = "feat_t2"
names(df2)[names(df2)=="logmove"] = "logmove_t2"
lagged_RF <- merge(lagged, df2, by=c("brand","store","week"))

#Repeat entire process with additional lag
df3 <- oj
df2$week<-df1$week+3  
df3 <- df3[myvars]
names(df3)[names(df3)=="price"] = "price_t3"
names(df3)[names(df3)=="feat"] = "feat_t3"
names(df3)[names(df3)=="logmove"] = "logmove_t3"
lagged_RF <- merge(lagged_RF, df3, by=c("brand","store","week"))

#drop unknown features to avoid spliting on these features.
lagged_RF$SSTRDIST <- NULL
lagged_RF$SSTRVOL <- NULL
lagged_RF$CPWVOL5 <- NULL
lagged_RF$CPDIST5 <- NULL

fit<-rpart(as.formula(logmove ~ AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                      +price_t1+feat_t1+price_t2+feat_t2+price_t3+feat_t3)
                      ,data=lagged_RF, method="anova",cp=0.06)

lagged_RF$leaf = fit$where
```

```{r echo=TRUE, message=FALSE}
#seperate the dataset by leaf
lagged_RF_3 <- subset(lagged_RF,leaf==3)
lagged_RF_4 <- subset(lagged_RF,leaf==4)
lagged_RF_5 <- subset(lagged_RF,leaf==5)

#seperate by brand
lagged_RF_3_D <- subset(lagged_RF_3,brand=="dominicks")
lagged_RF_3_M <- subset(lagged_RF_3,brand=="minute.maid")
lagged_RF_3_T <- subset(lagged_RF_3,brand=="tropicana")
lagged_RF_4_D <- subset(lagged_RF_4,brand=="dominicks")
lagged_RF_4_M <- subset(lagged_RF_4,brand=="minute.maid")
lagged_RF_4_T <- subset(lagged_RF_4,brand=="tropicana")
lagged_RF_5_D <- subset(lagged_RF_5,brand=="dominicks")
lagged_RF_5_M <- subset(lagged_RF_5,brand=="minute.maid")
lagged_RF_5_T <- subset(lagged_RF_5,brand=="tropicana")
```

```{r echo=TRUE, message=FALSE}
#Dominicks rename 
names(lagged_RF_3_D)[names(lagged_RF_3_D)=="price_t3"] = "price_t3_D"
names(lagged_RF_3_D)[names(lagged_RF_3_D)=="price_t2"] = "price_t2_D"
names(lagged_RF_3_D)[names(lagged_RF_3_D)=="price_t1"] = "price_t1_D"
names(lagged_RF_3_D)[names(lagged_RF_3_D)=="price"] = "price_D"

names(lagged_RF_3_D)[names(lagged_RF_3_D)=="feat_t3"] = "feat_t3_D"
names(lagged_RF_3_D)[names(lagged_RF_3_D)=="feat_t2"] = "feat_t2_D"
names(lagged_RF_3_D)[names(lagged_RF_3_D)=="feat_t1"] = "feat_t1_D"
names(lagged_RF_3_D)[names(lagged_RF_3_D)=="feat"] = "feat_D"

names(lagged_RF_3_D)[names(lagged_RF_3_D)=="logmove_t3"] = "logmove_t3_D"
names(lagged_RF_3_D)[names(lagged_RF_3_D)=="logmove_t2"] = "logmove_t2_D"
names(lagged_RF_3_D)[names(lagged_RF_3_D)=="logmove_t1"] = "logmove_t1_D"
names(lagged_RF_3_D)[names(lagged_RF_3_D)=="logmove"] = "logmove_D"

names(lagged_RF_4_D)[names(lagged_RF_4_D)=="price_t3"] = "price_t3_D"
names(lagged_RF_4_D)[names(lagged_RF_4_D)=="price_t2"] = "price_t2_D"
names(lagged_RF_4_D)[names(lagged_RF_4_D)=="price_t1"] = "price_t1_D"
names(lagged_RF_4_D)[names(lagged_RF_4_D)=="price"] = "price_D"

names(lagged_RF_4_D)[names(lagged_RF_4_D)=="feat_t3"] = "feat_t3_D"
names(lagged_RF_4_D)[names(lagged_RF_4_D)=="feat_t2"] = "feat_t2_D"
names(lagged_RF_4_D)[names(lagged_RF_4_D)=="feat_t1"] = "feat_t1_D"
names(lagged_RF_4_D)[names(lagged_RF_4_D)=="feat"] = "feat_D"

names(lagged_RF_4_D)[names(lagged_RF_4_D)=="logmove_t3"] = "logmove_t3_D"
names(lagged_RF_4_D)[names(lagged_RF_4_D)=="logmove_t2"] = "logmove_t2_D"
names(lagged_RF_4_D)[names(lagged_RF_4_D)=="logmove_t1"] = "logmove_t1_D"
names(lagged_RF_4_D)[names(lagged_RF_4_D)=="logmove"] = "logmove_D"

names(lagged_RF_5_D)[names(lagged_RF_5_D)=="price_t3"] = "price_t3_D"
names(lagged_RF_5_D)[names(lagged_RF_5_D)=="price_t2"] = "price_t2_D"
names(lagged_RF_5_D)[names(lagged_RF_5_D)=="price_t1"] = "price_t1_D"
names(lagged_RF_5_D)[names(lagged_RF_5_D)=="price"] = "price_D"

names(lagged_RF_5_D)[names(lagged_RF_5_D)=="feat_t3"] = "feat_t3_D"
names(lagged_RF_5_D)[names(lagged_RF_5_D)=="feat_t2"] = "feat_t2_D"
names(lagged_RF_5_D)[names(lagged_RF_5_D)=="feat_t1"] = "feat_t1_D"
names(lagged_RF_5_D)[names(lagged_RF_5_D)=="feat"] = "feat_D"

names(lagged_RF_5_D)[names(lagged_RF_5_D)=="logmove_t3"] = "logmove_t3_D"
names(lagged_RF_5_D)[names(lagged_RF_5_D)=="logmove_t2"] = "logmove_t2_D"
names(lagged_RF_5_D)[names(lagged_RF_5_D)=="logmove_t1"] = "logmove_t1_D"
names(lagged_RF_5_D)[names(lagged_RF_5_D)=="logmove"] = "logmove_D"

#MM rename 
names(lagged_RF_3_M)[names(lagged_RF_3_M)=="price_t3"] = "price_t3_M"
names(lagged_RF_3_M)[names(lagged_RF_3_M)=="price_t2"] = "price_t2_M"
names(lagged_RF_3_M)[names(lagged_RF_3_M)=="price_t1"] = "price_t1_M"
names(lagged_RF_3_M)[names(lagged_RF_3_M)=="price"] = "price_M"

names(lagged_RF_3_M)[names(lagged_RF_3_M)=="feat_t3"] = "feat_t3_M"
names(lagged_RF_3_M)[names(lagged_RF_3_M)=="feat_t2"] = "feat_t2_M"
names(lagged_RF_3_M)[names(lagged_RF_3_M)=="feat_t1"] = "feat_t1_M"
names(lagged_RF_3_M)[names(lagged_RF_3_M)=="feat"] = "feat_M"

names(lagged_RF_3_M)[names(lagged_RF_3_M)=="logmove_t3"] = "logmove_t3_M"
names(lagged_RF_3_M)[names(lagged_RF_3_M)=="logmove_t2"] = "logmove_t2_M"
names(lagged_RF_3_M)[names(lagged_RF_3_M)=="logmove_t1"] = "logmove_t1_M"
names(lagged_RF_3_M)[names(lagged_RF_3_M)=="logmove"] = "logmove_M"

names(lagged_RF_4_M)[names(lagged_RF_4_M)=="price_t3"] = "price_t3_M"
names(lagged_RF_4_M)[names(lagged_RF_4_M)=="price_t2"] = "price_t2_M"
names(lagged_RF_4_M)[names(lagged_RF_4_M)=="price_t1"] = "price_t1_M"
names(lagged_RF_4_M)[names(lagged_RF_4_M)=="price"] = "price_M"

names(lagged_RF_4_M)[names(lagged_RF_4_M)=="feat_t3"] = "feat_t3_M"
names(lagged_RF_4_M)[names(lagged_RF_4_M)=="feat_t2"] = "feat_t2_M"
names(lagged_RF_4_M)[names(lagged_RF_4_M)=="feat_t1"] = "feat_t1_M"
names(lagged_RF_4_M)[names(lagged_RF_4_M)=="feat"] = "feat_M"

names(lagged_RF_4_M)[names(lagged_RF_4_M)=="logmove_t3"] = "logmove_t3_M"
names(lagged_RF_4_M)[names(lagged_RF_4_M)=="logmove_t2"] = "logmove_t2_M"
names(lagged_RF_4_M)[names(lagged_RF_4_M)=="logmove_t1"] = "logmove_t1_M"
names(lagged_RF_4_M)[names(lagged_RF_4_M)=="logmove"] = "logmove_M"

names(lagged_RF_5_M)[names(lagged_RF_5_M)=="price_t3"] = "price_t3_M"
names(lagged_RF_5_M)[names(lagged_RF_5_M)=="price_t2"] = "price_t2_M"
names(lagged_RF_5_M)[names(lagged_RF_5_M)=="price_t1"] = "price_t1_M"
names(lagged_RF_5_M)[names(lagged_RF_5_M)=="price"] = "price_M"

names(lagged_RF_5_M)[names(lagged_RF_5_M)=="feat_t3"] = "feat_t3_M"
names(lagged_RF_5_M)[names(lagged_RF_5_M)=="feat_t2"] = "feat_t2_M"
names(lagged_RF_5_M)[names(lagged_RF_5_M)=="feat_t1"] = "feat_t1_M"
names(lagged_RF_5_M)[names(lagged_RF_5_M)=="feat"] = "feat_M"

names(lagged_RF_5_M)[names(lagged_RF_5_M)=="logmove_t3"] = "logmove_t3_M"
names(lagged_RF_5_M)[names(lagged_RF_5_M)=="logmove_t2"] = "logmove_t2_M"
names(lagged_RF_5_M)[names(lagged_RF_5_M)=="logmove_t1"] = "logmove_t1_M"
names(lagged_RF_5_M)[names(lagged_RF_5_M)=="logmove"] = "logmove_M"

#Trop rename 
names(lagged_RF_3_T)[names(lagged_RF_3_T)=="price_t3"] = "price_t3_T"
names(lagged_RF_3_T)[names(lagged_RF_3_T)=="price_t2"] = "price_t2_T"
names(lagged_RF_3_T)[names(lagged_RF_3_T)=="price_t1"] = "price_t1_T"
names(lagged_RF_3_T)[names(lagged_RF_3_T)=="price"] = "price_T"

names(lagged_RF_3_T)[names(lagged_RF_3_T)=="feat_t3"] = "feat_t3_T"
names(lagged_RF_3_T)[names(lagged_RF_3_T)=="feat_t2"] = "feat_t2_T"
names(lagged_RF_3_T)[names(lagged_RF_3_T)=="feat_t1"] = "feat_t1_T"
names(lagged_RF_3_T)[names(lagged_RF_3_T)=="feat"] = "feat_T"

names(lagged_RF_3_T)[names(lagged_RF_3_T)=="logmove_t3"] = "logmove_t3_T"
names(lagged_RF_3_T)[names(lagged_RF_3_T)=="logmove_t2"] = "logmove_t2_T"
names(lagged_RF_3_T)[names(lagged_RF_3_T)=="logmove_t1"] = "logmove_t1_T"
names(lagged_RF_3_T)[names(lagged_RF_3_T)=="logmove"] = "logmove_T"

names(lagged_RF_4_T)[names(lagged_RF_4_T)=="price_t3"] = "price_t3_T"
names(lagged_RF_4_T)[names(lagged_RF_4_T)=="price_t2"] = "price_t2_T"
names(lagged_RF_4_T)[names(lagged_RF_4_T)=="price_t1"] = "price_t1_T"
names(lagged_RF_4_T)[names(lagged_RF_4_T)=="price"] = "price_T"

names(lagged_RF_4_T)[names(lagged_RF_4_T)=="feat_t3"] = "feat_t3_T"
names(lagged_RF_4_T)[names(lagged_RF_4_T)=="feat_t2"] = "feat_t2_T"
names(lagged_RF_4_T)[names(lagged_RF_4_T)=="feat_t1"] = "feat_t1_T"
names(lagged_RF_4_T)[names(lagged_RF_4_T)=="feat"] = "feat_T"

names(lagged_RF_4_T)[names(lagged_RF_4_T)=="logmove_t3"] = "logmove_t3_T"
names(lagged_RF_4_T)[names(lagged_RF_4_T)=="logmove_t2"] = "logmove_t2_T"
names(lagged_RF_4_T)[names(lagged_RF_4_T)=="logmove_t1"] = "logmove_t1_T"
names(lagged_RF_4_T)[names(lagged_RF_4_T)=="logmove"] = "logmove_T"

names(lagged_RF_5_T)[names(lagged_RF_5_T)=="price_t3"] = "price_t3_T"
names(lagged_RF_5_T)[names(lagged_RF_5_T)=="price_t2"] = "price_t2_T"
names(lagged_RF_5_T)[names(lagged_RF_5_T)=="price_t1"] = "price_t1_T"
names(lagged_RF_5_T)[names(lagged_RF_5_T)=="price"] = "price_T"

names(lagged_RF_5_T)[names(lagged_RF_5_T)=="feat_t3"] = "feat_t3_T"
names(lagged_RF_5_T)[names(lagged_RF_5_T)=="feat_t2"] = "feat_t2_T"
names(lagged_RF_5_T)[names(lagged_RF_5_T)=="feat_t1"] = "feat_t1_T"
names(lagged_RF_5_T)[names(lagged_RF_5_T)=="feat"] = "feat_T"

names(lagged_RF_5_T)[names(lagged_RF_5_T)=="logmove_t3"] = "logmove_t3_T"
names(lagged_RF_5_T)[names(lagged_RF_5_T)=="logmove_t2"] = "logmove_t2_T"
names(lagged_RF_5_T)[names(lagged_RF_5_T)=="logmove_t1"] = "logmove_t1_T"
names(lagged_RF_5_T)[names(lagged_RF_5_T)=="logmove"] = "logmove_T"
```

```{r echo=TRUE, message=FALSE}
#leaf 3 Dominicks
DQ <- lagged_RF_3_D
Q3D.rf <- randomForest(logmove_D ~ AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                                   +price_t1_D+feat_t1_D
                                   +price_t2_D+feat_t2_D
                                   +price_t3_D+feat_t3_D, data = DQ, ntree = 100, keep.forest = TRUE)
DQ$pred_logmove_D = predict(Q3D.rf)
DQ$resid_Q3D <- DQ$logmove_D- DQ$pred_logmove_D
DP <- lagged_RF_3_D
P3D.rf <- randomForest(log(price_D) ~AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                                   +price_t1_D+feat_t1_D
                                   +price_t2_D+feat_t2_D
                                   +price_t3_D+feat_t3_D, data = DP, ntree = 100, keep.forest = TRUE)
DP$pred_logprice_D = predict(P3D.rf)
DP$resid_logP_D <- log(DP$price_D)- DP$pred_logprice_D
```

```{r echo=TRUE, message=FALSE}
#leaf 3 MM
MQ <- lagged_RF_3_M
Q3M.rf <- randomForest(logmove_M ~ AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_M+feat_t1_M
                       +price_t2_M+feat_t2_M
                       +price_t3_M+feat_t3_M, data = MQ, ntree = 100, keep.forest = TRUE)
MQ$pred_logmove_M = predict(Q3M.rf)
MQ$resid_Q3M <- MQ$logmove_M- MQ$pred_logmove_M
MP <- lagged_RF_3_M
P3M.rf <- randomForest(log(price_M) ~AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_M+feat_t1_M
                       +price_t2_M+feat_t2_M
                       +price_t3_M+feat_t3_M, data = MP, ntree = 100, keep.forest = TRUE)
MP$pred_logprice_M = predict(P3M.rf)
MP$resid_logP_M <- log(MP$price_M)- MP$pred_logprice_M
```

```{r echo=TRUE, message=FALSE}
#leaf 3 Trop
TQ <- lagged_RF_3_T
Q3T.rf <- randomForest(logmove_T ~ AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_T+feat_t1_T
                       +price_t2_T+feat_t2_T
                       +price_t3_T+feat_t3_T, data = TQ, ntree = 100, keep.forest = TRUE)
TQ$pred_logmove_T = predict(Q3T.rf)
TQ$resid_Q3T <- TQ$logmove_T- TQ$pred_logmove_T
TP <- lagged_RF_3_T
P3T.rf <- randomForest(log(price_T) ~AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_T+feat_t1_T
                       +price_t2_T+feat_t2_T
                       +price_t3_T+feat_t3_T, data = TP, ntree = 100, keep.forest = TRUE)
TP$pred_logprice_T = predict(P3T.rf)
TP$resid_logP_T <- log(TP$price_T)- TP$pred_logprice_T
```


```{r echo=TRUE, message=FALSE}
#leaf 3 elasticity matrix
rownames = c("Q Trop", "Q MM", "Q Dom")
colnames = c("P Trop", "P MM", "P Dom")
Elast_matrix <- matrix(3,3,3, dimnames = list(rownames, colnames))

myvars_M <- c("feat_t3_M", "feat_t2_M", "feat_t1_M","feat_M", 
              "price_t3_M", "price_t2_M", "price_t1_M","price_M","store","week")
temp_M <- lagged_RF_3_M[myvars_M]

temp_DP <- DP[c("store","week", "resid_logP_D")]
temp_MP <- MP[c("store","week", "resid_logP_M")]
temp_TP <- TP[c("store","week", "resid_logP_T")]

TQ <- merge(TQ, temp_DP, by=c("store","week"))
TQ <- merge(TQ, temp_MP, by=c("store","week"))
TQ <- merge(TQ, temp_TP, by=c("store","week"))

MQ <- merge(MQ, temp_DP, by=c("store","week"))
MQ <- merge(MQ, temp_MP, by=c("store","week"))
MQ <- merge(MQ, temp_TP, by=c("store","week"))

DQ <- merge(DQ, temp_DP, by=c("store","week"))
DQ <- merge(DQ, temp_MP, by=c("store","week"))
DQ <- merge(DQ, temp_TP, by=c("store","week"))
```

```{r}
D_reg = glm(resid_Q3D ~ resid_logP_D + resid_logP_M + resid_logP_T, data=DQ)
M_reg = glm(resid_Q3M ~ resid_logP_D + resid_logP_M + resid_logP_T, data=MQ)
T_reg = glm(resid_Q3T ~ resid_logP_D + resid_logP_M + resid_logP_T, data=TQ)
```

```{r echo=TRUE}
Elast_matrix[1,1] <- coef(T_reg)["resid_logP_T"] 
Elast_matrix[1,2] <- coef(T_reg)["resid_logP_M"] 
Elast_matrix[1,3] <- coef(T_reg)["resid_logP_D"] 
Elast_matrix[2,1] <- coef(M_reg)["resid_logP_T"] 
Elast_matrix[2,2] <- coef(M_reg)["resid_logP_M"]
Elast_matrix[2,3] <- coef(M_reg)["resid_logP_D"] 
Elast_matrix[3,1] <- coef(D_reg)["resid_logP_T"] 
Elast_matrix[3,2] <- coef(D_reg)["resid_logP_M"]  
Elast_matrix[3,3] <- coef(D_reg)["resid_logP_D"]  
Elast_matrix
```

```{r echo=TRUE, message=FALSE}
#leaf 4 Dominicks
DQ4 <- lagged_RF_4_D
Q4D.rf <- randomForest(logmove_D ~ AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                                   +price_t1_D+feat_t1_D
                                   +price_t2_D+feat_t2_D
                                   +price_t3_D+feat_t3_D, data = DQ4, ntree = 100, keep.forest = TRUE)
DQ4$pred_logmove_D = predict(Q4D.rf)
DQ4$resid_Q4D <- DQ4$logmove_D- DQ4$pred_logmove_D
DP4 <- lagged_RF_4_D
P4D.rf <- randomForest(log(price_D) ~AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                                   +price_t1_D+feat_t1_D
                                   +price_t2_D+feat_t2_D
                                   +price_t3_D+feat_t3_D, data = DP4, ntree = 100, keep.forest = TRUE)
DP4$pred_logprice_D = predict(P4D.rf)
DP4$resid_logP_D <- log(DP4$price_D)- DP4$pred_logprice_D
```

```{r echo=TRUE, message=FALSE}
#leaf 4 MM
MQ4 <- lagged_RF_4_M
Q4M.rf <- randomForest(logmove_M ~ AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_M+feat_t1_M
                       +price_t2_M+feat_t2_M
                       +price_t3_M+feat_t3_M, data = MQ4, ntree = 100, keep.forest = TRUE)
MQ4$pred_logmove_M = predict(Q4M.rf)
MQ4$resid_Q4M <- MQ4$logmove_M- MQ4$pred_logmove_M
MP4 <- lagged_RF_4_M
P4M.rf <- randomForest(log(price_M) ~AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_M+feat_t1_M
                       +price_t2_M+feat_t2_M
                       +price_t3_M+feat_t3_M, data = MP4, ntree = 100, keep.forest = TRUE)
MP4$pred_logprice_M = predict(P4M.rf)
MP4$resid_logP_M <- log(MP4$price_M)- MP4$pred_logprice_M
```

```{r echo=TRUE, message=FALSE}
#leaf 4 Trop
TQ4 <- lagged_RF_4_T
Q4T.rf <- randomForest(logmove_T ~ AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_T+feat_t1_T
                       +price_t2_T+feat_t2_T
                       +price_t3_T+feat_t3_T, data = TQ4, ntree = 100, keep.forest = TRUE)
TQ4$pred_logmove_T = predict(Q4T.rf)
TQ4$resid_Q4T <- TQ4$logmove_T- TQ4$pred_logmove_T
TP4 <- lagged_RF_4_T
P4T.rf <- randomForest(log(price_T) ~AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_T+feat_t1_T
                       +price_t2_T+feat_t2_T
                       +price_t3_T+feat_t3_T, data = TP4, ntree = 100, keep.forest = TRUE)
TP4$pred_logprice_T = predict(P4T.rf)
TP4$resid_logP_T <- log(TP4$price_T)- TP4$pred_logprice_T
```

```{r echo=TRUE, message=FALSE}
#leaf 4 elasticity matrix
rownames = c("Q Trop", "Q MM", "Q Dom")
colnames = c("P Trop", "P MM", "P Dom")
Elast_matrix <- matrix(3,3,3, dimnames = list(rownames, colnames))

myvars_M <- c("feat_t3_M", "feat_t2_M", "feat_t1_M","feat_M", 
              "price_t3_M", "price_t2_M", "price_t1_M","price_M","store","week")
temp_M <- lagged_RF_3_M[myvars_M]

temp_DP4 <- DP4[c("store","week", "resid_logP_D")]
temp_MP4 <- MP4[c("store","week", "resid_logP_M")]
temp_TP4 <- TP4[c("store","week", "resid_logP_T")]

TQ4 <- merge(TQ4, temp_DP4, by=c("store","week"))
TQ4 <- merge(TQ4, temp_MP4, by=c("store","week"))
TQ4 <- merge(TQ4, temp_TP4, by=c("store","week"))

MQ4 <- merge(MQ4, temp_DP4, by=c("store","week"))
MQ4 <- merge(MQ4, temp_MP4, by=c("store","week"))
MQ4 <- merge(MQ4, temp_TP4, by=c("store","week"))

DQ4 <- merge(DQ4, temp_DP4, by=c("store","week"))
DQ4 <- merge(DQ4, temp_MP4, by=c("store","week"))
DQ4 <- merge(DQ4, temp_TP4, by=c("store","week"))

D_reg = glm(resid_Q4D ~ resid_logP_D + resid_logP_M + resid_logP_T, data=DQ4)
M_reg = glm(resid_Q4M ~ resid_logP_D + resid_logP_M + resid_logP_T, data=MQ4)
T_reg = glm(resid_Q4T ~ resid_logP_D + resid_logP_M + resid_logP_T, data=TQ4)
```

```{r echo=TRUE}
Elast_matrix[1,1] <- coef(T_reg)["resid_logP_T"] 
Elast_matrix[1,2] <- coef(T_reg)["resid_logP_M"] 
Elast_matrix[1,3] <- coef(T_reg)["resid_logP_D"] 
Elast_matrix[2,1] <- coef(M_reg)["resid_logP_T"] 
Elast_matrix[2,2] <- coef(M_reg)["resid_logP_M"]
Elast_matrix[2,3] <- coef(M_reg)["resid_logP_D"] 
Elast_matrix[3,1] <- coef(D_reg)["resid_logP_T"] 
Elast_matrix[3,2] <- coef(D_reg)["resid_logP_M"]  
Elast_matrix[3,3] <- coef(D_reg)["resid_logP_D"]  
Elast_matrix
```

```{r echo=TRUE, message=FALSE}
#leaf 5 Dominicks
DQ5 <- lagged_RF_5_D
Q5D.rf <- randomForest(logmove_D ~ AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                                   +price_t1_D+feat_t1_D
                                   +price_t2_D+feat_t2_D
                                   +price_t3_D+feat_t3_D, data = DQ5, ntree = 100, keep.forest = TRUE)
DQ5$pred_logmove_D = predict(Q5D.rf)
DQ5$resid_Q5D <- DQ5$logmove_D- DQ5$pred_logmove_D
DP5 <- lagged_RF_5_D
P5D.rf <- randomForest(log(price_D) ~AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                                   +price_t1_D+feat_t1_D
                                   +price_t2_D+feat_t2_D
                                   +price_t3_D+feat_t3_D, data = DP5, ntree = 100, keep.forest = TRUE)
DP5$pred_logprice_D = predict(P5D.rf)
DP5$resid_logP_D <- log(DP5$price_D)- DP5$pred_logprice_D
```

```{r echo=TRUE, message=FALSE}
#leaf 5 MM
MQ5 <- lagged_RF_5_M
Q5M.rf <- randomForest(logmove_M ~ AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_M+feat_t1_M
                       +price_t2_M+feat_t2_M
                       +price_t3_M+feat_t3_M, data = MQ5, ntree = 100, keep.forest = TRUE)
MQ5$pred_logmove_M = predict(Q5M.rf)
MQ5$resid_Q5M <- MQ5$logmove_M- MQ5$pred_logmove_M
MP5 <- lagged_RF_5_M
P5M.rf <- randomForest(log(price_M) ~AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_M+feat_t1_M
                       +price_t2_M+feat_t2_M
                       +price_t3_M+feat_t3_M, data = MP5, ntree = 100, keep.forest = TRUE)
MP5$pred_logprice_M = predict(P5M.rf)
MP5$resid_logP_M <- log(MP5$price_M)- MP5$pred_logprice_M
```

```{r echo=TRUE, message=FALSE}
#leaf 5 Trop
TQ5 <- lagged_RF_5_T
Q5T.rf <- randomForest(logmove_T ~ AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_T+feat_t1_T
                       +price_t2_T+feat_t2_T
                       +price_t3_T+feat_t3_T, data = TQ5, ntree = 100, keep.forest = TRUE)
TQ5$pred_logmove_T = predict(Q5T.rf)
TQ5$resid_Q5T <- TQ5$logmove_T- TQ5$pred_logmove_T
TP5 <- lagged_RF_5_T
P5T.rf <- randomForest(log(price_T) ~AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                       +price_t1_T+feat_t1_T
                       +price_t2_T+feat_t2_T
                       +price_t3_T+feat_t3_T, data = TP5, ntree = 100, keep.forest = TRUE)
TP5$pred_logprice_T = predict(P5T.rf)
TP5$resid_logP_T <- log(TP5$price_T)- TP5$pred_logprice_T
```

```{r echo=TRUE, message=FALSE}
#leaf 5 elasticity matrix
rownames = c("Q Trop", "Q MM", "Q Dom")
colnames = c("P Trop", "P MM", "P Dom")
Elast_matrix <- matrix(3,3,3, dimnames = list(rownames, colnames))

myvars_M <- c("feat_t3_M", "feat_t2_M", "feat_t1_M","feat_M", 
              "price_t3_M", "price_t2_M", "price_t1_M","price_M","store","week")
temp_M <- lagged_RF_3_M[myvars_M]

temp_DP5 <- DP5[c("store","week", "resid_logP_D")]
temp_MP5 <- MP5[c("store","week", "resid_logP_M")]
temp_TP5 <- TP5[c("store","week", "resid_logP_T")]

TQ5 <- merge(TQ5, temp_DP5, by=c("store","week"))
TQ5 <- merge(TQ5, temp_MP5, by=c("store","week"))
TQ5 <- merge(TQ5, temp_TP5, by=c("store","week"))

MQ5 <- merge(MQ5, temp_DP5, by=c("store","week"))
MQ5 <- merge(MQ5, temp_MP5, by=c("store","week"))
MQ5 <- merge(MQ5, temp_TP5, by=c("store","week"))

DQ5 <- merge(DQ5, temp_DP5, by=c("store","week"))
DQ5 <- merge(DQ5, temp_MP5, by=c("store","week"))
DQ5 <- merge(DQ5, temp_TP5, by=c("store","week"))

D_reg = glm(resid_Q5D ~ resid_logP_D + resid_logP_M + resid_logP_T, data=DQ5)
M_reg = glm(resid_Q5M ~ resid_logP_D + resid_logP_M + resid_logP_T, data=MQ5)
T_reg = glm(resid_Q5T ~ resid_logP_D + resid_logP_M + resid_logP_T, data=TQ5)
```

```{r echo=TRUE}
Elast_matrix[1,1] <- coef(T_reg)["resid_logP_T"] 
Elast_matrix[1,2] <- coef(T_reg)["resid_logP_M"] 
Elast_matrix[1,3] <- coef(T_reg)["resid_logP_D"] 
Elast_matrix[2,1] <- coef(M_reg)["resid_logP_T"] 
Elast_matrix[2,2] <- coef(M_reg)["resid_logP_M"]
Elast_matrix[2,3] <- coef(M_reg)["resid_logP_D"] 
Elast_matrix[3,1] <- coef(D_reg)["resid_logP_T"] 
Elast_matrix[3,2] <- coef(D_reg)["resid_logP_M"]  
Elast_matrix[3,3] <- coef(D_reg)["resid_logP_D"]  
Elast_matrix
```

```{r echo=TRUE, message=FALSE}
library(ggplot2)
fig_DP<-ggplot(DP5, aes(pred_logprice_D,log(price_D)))+geom_point() + geom_smooth(method='lm') + geom_abline(intercept = 0, slope =1)
fig_DP 
```


```{r echo=TRUE, message=FALSE}
fit_ols <- lm(log(price_D) ~AGE60+EDUC+ETHNIC+INCOME+HHLARGE+WORKWOM+HVAL150
                                   +price_t1_D+feat_t1_D
                                   +price_t2_D+feat_t2_D
                                   +price_t3_D+feat_t3_D, data = DP5)

DP5$pred_logprice_D = predict(fit_ols)
DP5$resid_logP_D <- log(DP5$price_D)- DP5$pred_logprice_D

fig_DP_ols<-ggplot(DP, aes(pred_logprice_D,log(price_D)))+geom_point() + geom_smooth(method='lm') + geom_abline(intercept = 0, slope =1)
fig_DP 
```

